# Generated by Django 3.1.7 on 2021-03-18 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Tên sản phẩm')),
                ('price_num_1', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 1')),
                ('price_num_2', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 2')),
                ('price_num_5', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 5')),
                ('price_num_10', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 10')),
                ('price_num_50', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 50')),
                ('price_num_100', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 100')),
                ('price_num_200', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 200')),
                ('price_num_300', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 300')),
                ('price_num_500', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 500')),
                ('price_num_1000', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 1000')),
                ('price_num_2000', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 2000')),
                ('price_num_3500', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 3500')),
                ('price_num_5000', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 5000')),
                ('price_num_7500', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 7500')),
                ('price_num_10000', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 10000')),
                ('price_num_15000', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 15000')),
                ('price_num_20000', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 20000')),
                ('price_num_40000', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 40000')),
                ('price_num_65000', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 65000')),
                ('price_num_90000', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 90000')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_32b', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_16b', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_8b', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_4b', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_2b', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_1b', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_500m', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_300m', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_150m', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_60m', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_30m', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('discount_10m', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_media', to='api.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discount',
            },
        ),
    ]
