# Generated by Django 3.1.7 on 2021-03-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_num_25',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 25'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_num_3',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Giá số lượng 3'),
        ),
    ]
