# Generated by Django 3.1.7 on 2021-03-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210318_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_10m',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 10tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_150m',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 150tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_16b',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 16 tỷ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_1b',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 1 tỷ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_2b',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 2 tỷ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_300m',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 300tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_30m',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 30tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_4b',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 4 tỷ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_500m',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu  500tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_60m',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 60tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_8b',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Chiết khấu 8 tỷ'),
        ),
    ]
