# Generated by Django 3.1.7 on 2021-03-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210318_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_10m',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 10tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_150m',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 150tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_16b',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 16 tỷ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_1b',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 1 tỷ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_2b',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 2 tỷ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_300m',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 300tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_30m',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 30tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_32b',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 32 tỷ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_4b',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 4 tỷ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_500m',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu  500tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_60m',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 60tr'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_8b',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Chiết khấu 8 tỷ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_1',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_10',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 10'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_100',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 100'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_1000',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 1000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_10000',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 10000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_15000',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 15000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_200',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 200'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_2000',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 2000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_20000',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 20000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_25',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 25'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_300',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 300'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_3500',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 3500'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_40000',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 40000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_5',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_50',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 50'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_500',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 500'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_5000',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 5000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_65000',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 65000'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_7500',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 7500'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_num_90000',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Giá số lượng 90000'),
        ),
    ]
