# Generated by Django 3.1.7 on 2021-03-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210319_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_num_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_1000',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_10000',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_15000',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_200',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_2000',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_20000',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_25',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_300',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_3500',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_40000',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_50',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_500',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_5000',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_65000',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_7500',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_num_90000',
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Tên giá')),
                ('price_of', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Giá ứng với số lượng')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('product', models.ManyToManyField(to='api.Product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Amount',
                'verbose_name_plural': 'Amounts',
                'db_table': 'amount',
            },
        ),
    ]
